language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker

jobs:
  include:
    - stage: Create XML report
      script: mvn clean checkstyle:checkstyle

    - stage: Create Checkstyle HTML report from XML report, upload to S3
      install: skip
      before_script:
        - mkdir $TRAVIS_BUILD_DIR/target/checkstyle-html-report/
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker pull schultedev/checkstyle-xml-to-html
      script:
        - docker run -v $TRAVIS_BUILD_DIR/target/checkstyle-result.xml:/checkstyle-result.xml:ro \
            -v $TRAVIS_BUILD_DIR/target/checkstyle-html-report/:/tmp/checkstyle-html-report/ \
            -u $USER schultedev/checkstyle-xml-to-html:latest
      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: $S3_KEY_PREFIX/$TRAVIS_BRANCH/checkstyle/
          local_dir: $TRAVIS_BUILD_DIR/target/checkstyle-html-report/
          region: "eu-central-1"
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: $S3_KEY_PREFIX/$TRAVIS_COMMIT/checkstyle/
          local_dir: $TRAVIS_BUILD_DIR/target/checkstyle-html-report/
          region: "eu-central-1"
