language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
sudo: required
services:
  - docker

before_script:
  - mkdir $TRAVIS_BUILD_DIR/target/checkstyle-html-report/
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull schultedev/checkstyle-xml-to-html
script:
  - mvn clean checkstyle:checkstyle
  - docker run -u $USER \
      -v $TRAVIS_BUILD_DIR/target/checkstyle-result.xml:/checkstyle-result.xml:ro \
      -v $TRAVIS_BUILD_DIR/target/checkstyle-html-report/:/tmp/checkstyle-html-report/ \
      schultedev/checkstyle-xml-to-html:latest
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_KEY_PREFIX/$TRAVIS_BRANCH/checkstyle/
    local_dir: $TRAVIS_BUILD_DIR/target/checkstyle-html-report/
    region: "eu-central-1"
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_KEY_PREFIX/$TRAVIS_COMMIT/checkstyle/
    local_dir: $TRAVIS_BUILD_DIR/target/checkstyle-html-report/
    region: "eu-central-1"
